### ISSUE TITLE
HyperPixel incompatible with 64 bit RPi OS

### ISSUE THREAD

**Issue by ifurusato** [pimoroni/hyperpixel4#129] opened 2021-04-14 09:36 UTC
**Describe the bug**

I'm currently using the beta of the Raspberry Pi OS. I've been able to successfully install and use a rectangular HyperPixel 4 display on both a Pi 3 B+ and a Pi 4 using the existing, current 32 bit OS. When I try to install using curl (as recommended) I receive a message "This hardware is not supported, sorry! Config files have been left untouched".

I completely realise that currently the 64 bit OS is beta and that it may not support the HyperPixel. I'm creating this Issue to flag a potential problem when the 64 bit OS is released. 

**To Reproduce**

I installed the RPi 64 bit beta on a clean SD card, got the Pi 4 up and running, then ran "curl https://get.pimoroni.com/hyperpixel4 | bash". Whereas this worked on the same Pi 4 using the 32 bit OS, it fails as described when using the 64 bit OS.

**Your HyperPixel 4**

It's a rectangular, non-touch HyperPixel, received April 2021. It's plugged directly to the Pi 4's GPIO pins. This HyperPixel display works fine on either a RPi 3 B+ or a Pi 4 when using the 32 bit OS. As recommended, when swapping the same SD card between Pi 3 and 4, I re-install the software.

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly

This is a Pi 4, revision do3114.

2. Which OS release are you using: `lsb_release --description` and `uname -r`

Debian GNU/Linux 10 (buster); 5.10.17-v8+; uname -m returns "aarch64"

3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on?

Brand-new installation, python upgraded to 3.8.5.

**Extra debugging information**

 Not using touch.

**Comment by Gadgetoid** [comment] 2021-05-20 10:26
dupe of #117

**Closed by Gadgetoid** 2021-05-20 10:26 UTC
Labels: bug
