### ISSUE TITLE
HyperPixel 4.0 Touch black screen after Pi updates

### ISSUE THREAD

**Issue by morphias2004** [pimoroni/hyperpixel4#88] opened 2020-07-25 06:18 UTC
**Describe the bug**

I previously opened this as a faulty on the OctoDash GitHub page:  https://github.com/UnchartedBull/OctoDash/issues/848

I have since conclusively ruled out OctoDash as a factor as a clean installation of OctoPrint/OctoPi, installing the HyperPixel 4 drivers and then running **sudo apt update** and **sudo apt full-upgrade** causes the issue.

This points to the HyperPixel 4 drivers having an issue with the latest Pi updates.

**To Reproduce**

Image SD card with the current OctoPi image

https://octopi.octoprint.org/latest

Update to Octoprint 1.4.0 from within OctoPi web interface and reboot.

Install HyperPixel 4 driver and reboot.

curl https://get.pimoroni.com/hyperpixel4 | bash

Screen is working correctly at this point and is in 'portait'.

Run latest Pi updates

sudo apt update

sudo apt full-upgrade

Reboot and you get a black screen. OctoPi is up and running and available via the web interface and SSH.

**Your HyperPixel 4**

Let us know which HyperPixel 4 board you're using. Note: if you're having a problem with the original HyperPixel you should go to: https://github.com/pimoroni/hyperpixel

1. Is it Square or Rectangular?
**Rectangular**

2. Touch or non Touch?
**Touch**

3. Approximately when was it purchased
**2 months ago**

4. How is it connected to your Pi
**Direct GPIO onto Raspberry Pi 4 4GB**

**Your Raspberry Pi**

Give as much detail about your Pi and OS as possible. We only officially support Raspbian, but might be able to point you in the right direction if the problem is with another OS.

1. What model of Raspberry Pi are you using (the result of `cat /proc/cpuinfo | grep Revision` can tell us this exactly
**c03112**

2. Which OS release are you using: `lsb_release --description` and `uname -r`
**Raspbian GNU/Linux 10 (buster)
4.19.75-v7l+**

3. Is this a fresh OS setup, or one you might have previously installed scripts/add-ons on?
**Fresh**

**Extra debugging information**

If you're having a problem with touch, try checking `dmesg` for related errors:

* `dmesg | grep Goodix` for HyperPixel 4.0" Rectangular
**Blank response to that command**

* `dmesg | grep ft5` for HyperPixel 4.0" Square

And check i2c is working:

`ls /dev/i2c-*`

You should see something like:

```text
pi@raspberrypi:~ $ ls /dev/i2c-*
/dev/i2c-7
```
**Command fails
ls: cannot access '/dev/i2c-*': No such file or directory**

And your HyperPixel 4 touch is showing up (there should be an address blocked out with UU in the below command):

`i2cdetect -y X` ( where X is the number of i2c bus found in the command above)

For example:

```text
pi@raspberrypi:~ $ i2cdetect -y 7
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- UU -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Command fails
-bash: i2cdetect: command not found**

Here is the list of updates loaded by the **sudo apt update**:

pi@octopi:~ $ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
libllvm8 rpi-eeprom-images
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
busybox initramfs-tools initramfs-tools-core klibc-utils libfl2 libklibc libllvm9 linux-base pigz rpi.gpio-common
The following packages will be upgraded:
apt apt-utils base-files bind9-host binutils binutils-arm-linux-gnueabihf binutils-common bluez bluez-firmware ca-certificates cron curl dhcpcd5
distro-info-data dphys-swapfile e2fsprogs ffmpeg file firmware-atheros firmware-brcm80211 firmware-libertas firmware-misc-nonfree firmware-realtek
freetype2-doc fuse git git-man imagemagick imagemagick-6-common imagemagick-6.q16 iputils-ping libapt-inst2.0 libapt-pkg5.0 libarchive13 libavcodec58
libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libbind9-161 libbinutils libcom-err2 libcurl3-gnutls libcurl4 libdns-export1104
libdns1104 libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libext2fs2 libfreetype6 libfreetype6-dev libfribidi0 libfuse2 libgl1-mesa-dri
libglib2.0-0 libglib2.0-data libgnutls30 libicu63 libidn2-0 libisc-export1100 libisc1100 libisccc161 libisccfg163 libldap-2.4-2 libldap-common liblwres161
libmagic-mgc libmagic1 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmysofa0 libncurses6 libncursesw5 libncursesw6 libopenjp2-7 libopenmpt0
libpam-chksshpwd libpam-modules libpam-modules-bin libpam-runtime libpam-systemd libpam0g libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpostproc55
libpython2.7 libpython2.7-dev libpython2.7-minimal libpython2.7-stdlib libpython3.7 libpython3.7-minimal libpython3.7-stdlib libraspberrypi-bin
libraspberrypi-dev libraspberrypi-doc libraspberrypi0 libsasl2-2 libsasl2-modules-db libss2 libssh-gcrypt-4 libssl-dev libssl1.1 libswresample3 libswscale5
libsystemd0 libtiff5 libtinfo5 libtinfo6 libudev1 libvpx5 libxml2 libxmuu1 ncurses-base ncurses-bin ncurses-term openssh-client openssh-server
openssh-sftp-server openssl pi-bluetooth python-apt-common python-rpi.gpio python2.7 python2.7-dev python2.7-minimal python3-apt python3.7 python3.7-minimal
raspberrypi-bootloader raspberrypi-kernel raspberrypi-sys-mods raspi-config rpcbind rpi-eeprom rpi-eeprom-images rpi-update ssh sudo systemd systemd-sysv
tzdata udev wpasupplicant
148 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 258 MB of archives.
After this operation, 116 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf libpam0g armhf 1.3.1-5+rpt2 [121 kB]
Get:4 http://archive.raspberrypi.org/debian buster/main armhf libpam-modules-bin armhf 1.3.1-5+rpt2 [103 kB]
Get:5 http://archive.raspberrypi.org/debian buster/main armhf libpam-modules armhf 1.3.1-5+rpt2 [290 kB]
Get:6 http://archive.raspberrypi.org/debian buster/main armhf libpam-runtime all 1.3.1-5+rpt2 [211 kB]
Get:8 http://archive.raspberrypi.org/debian buster/main armhf bluez armhf 5.50-1.2deb10u1+rpt1 [765 kB]
Get:10 http://archive.raspberrypi.org/debian buster/main armhf libssl-dev armhf 1.1.1d-0+deb10u3+rpt1 [1,583 kB]
Get:2 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf base-files armhf 10.3+rpi1+deb10u4 [70.0 kB]
Get:3 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf ncurses-bin armhf 6.1+20181013-2+deb10u2 [400 kB]
Get:7 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf ncurses-base all 6.1+20181013-2+deb10u2 [258 kB]
Get:9 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf systemd-sysv armhf 241-7deb10u4+rpi1 [100 kB]
Get:11 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libpam-systemd armhf 241-7deb10u4+rpi1 [194 kB]
Get:12 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libsystemd0 armhf 241-7deb10u4+rpi1 [305 kB]
Get:13 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf systemd armhf 241-7deb10u4+rpi1 [3,255 kB]
Get:14 http://archive.raspberrypi.org/debian buster/main armhf libssl1.1 armhf 1.1.1d-0+deb10u3+rpt1 [1,275 kB]
Get:15 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf udev armhf 241-7deb10u4+rpi1 [1,248 kB]
Get:16 http://archive.raspberrypi.org/debian buster/main armhf bluez-firmware all 1.2-4+rpt3 [120 kB]
Get:17 http://archive.raspberrypi.org/debian buster/main armhf openssl armhf 1.1.1d-0+deb10u3+rpt1 [807 kB]
Get:18 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libudev1 armhf 241-7deb10u4+rpi1 [144 kB]
Get:19 http://archive.raspberrypi.org/debian buster/main armhf dhcpcd5 armhf 1:8.1.2-1+rpt1 [146 kB]
Get:21 http://archive.raspberrypi.org/debian buster/main armhf dphys-swapfile all 20100506-5+rpt1 [21.4 kB]
Get:22 http://archive.raspberrypi.org/debian buster/main armhf ffmpeg armhf 7:4.1.6-1deb10u1+rpt1 [1,432 kB]
Get:20 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libglib2.0-0 armhf 2.58.3-2+deb10u2 [1,078 kB]
Get:23 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libidn2-0 armhf 2.0.5-1+deb10u1 [74.0 kB]
Get:24 http://archive.raspberrypi.org/debian buster/main armhf libavdevice58 armhf 7:4.1.6-1deb10u1+rpt1 [147 kB]
Get:25 http://archive.raspberrypi.org/debian buster/main armhf libavfilter7 armhf 7:4.1.6-1deb10u1+rpt1 [1,450 kB]
Get:26 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libgnutls30 armhf 3.6.7-4+deb10u4 [1,047 kB]
Get:27 http://archive.raspberrypi.org/debian buster/main armhf libswscale5 armhf 7:4.1.6-1deb10u1+rpt1 [253 kB]
Get:28 http://archive.raspberrypi.org/debian buster/main armhf libavformat58 armhf 7:4.1.6-1deb10u1+rpt1 [1,516 kB]
Get:31 http://archive.raspberrypi.org/debian buster/main armhf libavcodec58 armhf 7:4.1.6-1deb10u1+rpt1 [8,904 kB]
Get:29 http://mirror.datamossa.io/raspbian buster/main armhf libapt-pkg5.0 armhf 1.8.2.1 [855 kB]
Get:30 http://mirror.datamossa.io/raspbian buster/main armhf libapt-inst2.0 armhf 1.8.2.1 [199 kB]
Get:32 http://mirror.datamossa.io/raspbian buster/main armhf apt armhf 1.8.2.1 [1,349 kB]
Get:33 http://mirror.datamossa.io/raspbian buster/main armhf apt-utils armhf 1.8.2.1 [399 kB]
Get:34 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf libext2fs2 armhf 1.44.5-1+deb10u3 [202 kB]
Get:35 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf e2fsprogs armhf 1.44.5-1+deb10u3 [532 kB]
Get:36 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf cron armhf 3.0pl1-134+deb10u1 [94.0 kB]
Get:38 http://archive.raspberrypi.org/debian buster/main armhf libswresample3 armhf 7:4.1.6-1deb10u1+rpt1 [118 kB]
Get:39 http://archive.raspberrypi.org/debian buster/main armhf libpostproc55 armhf 7:4.1.6-1deb10u1+rpt1 [95.1 kB]
Get:40 http://archive.raspberrypi.org/debian buster/main armhf libavresample4 armhf 7:4.1.6-1deb10u1+rpt1 [104 kB]
Get:37 http://raspbian.melbourneitmirror.net/raspbian buster/main armhf freetype2-doc all 2.9.1-3+deb10u1 [2,309 kB]
Get:41 http://archive.raspberrypi.org/debian buster/main armhf libdrm-common all 2.4.100-4+rpi1bpo10+1 [14.4 kB]
Get:42 http://archive.raspberrypi.org/debian buster/main armhf libdrm2 armhf 2.4.100-4+rpi1bpo10+1 [36.6 kB]
Get:43 http://archive.raspberrypi.org/debian buster/main armhf libavutil56 armhf 7:4.1.6-1deb10u1+rpt1 [354 kB]
Get:44 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi-bin armhf 1.20200723-1 [340 kB]
Get:45 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi-doc armhf 1.20200723-1 [31.4 MB]
Get:46 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libfreetype6-dev armhf 2.9.1-3+deb10u1 [479 kB]
Get:47 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libfreetype6 armhf 2.9.1-3+deb10u1 [317 kB]
Get:48 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libopenjp2-7 armhf 2.3.0-2+deb10u1 [138 kB]
Get:49 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libtiff5 armhf 4.1.0+git191117-2deb10u1 [249 kB]
Get:50 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libicu63 armhf 63.1-6+deb10u1 [7,973 kB]
Get:51 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libxml2 armhf 2.9.4+dfsg1-7+b3 [571 kB]
Get:52 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf imagemagick-6-common all 8:6.9.10.23+dfsg-2.1+deb10u1 [200 kB]
Get:53 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmagickcore-6.q16-6 armhf 8:6.9.10.23+dfsg-2.1+deb10u1 [1,600 kB]
Get:55 http://mirror.datamossa.io/raspbian buster/main armhf pigz armhf 2.4-1 [47.2 kB]
Get:54 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmagickwand-6.q16-6 armhf 8:6.9.10.23+dfsg-2.1+deb10u1 [419 kB]
Get:56 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python2.7-dev armhf 2.7.16-2+deb10u1 [291 kB]
Get:57 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython2.7-dev armhf 2.7.16-2+deb10u1 [30.9 MB]
Get:65 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi-dev armhf 1.20200723-1 [412 kB]
Get:66 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel armhf 1.20200723-1 [73.0 MB]
Get:84 http://mirror.aarnet.edu.au/pub/raspbian/raspbian buster/main armhf ssh all 1:7.9p1-10+deb10u2 [202 kB]
Get:58 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython2.7 armhf 2.7.16-2+deb10u1 [873 kB]
Get:59 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python2.7 armhf 2.7.16-2+deb10u1 [305 kB]
Get:102 http://mirror.datamossa.io/raspbian buster/main armhf libfl2 armhf 2.6.4-6.2 [103 kB]
Get:60 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython2.7-stdlib armhf 2.7.16-2+deb10u1 [1,844 kB]
Get:61 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python2.7-minimal armhf 2.7.16-2+deb10u1 [1,091 kB]
Get:103 http://mirror.datamossa.io/raspbian buster/main armhf busybox armhf 1:1.30.1-4 [405 kB]
Get:62 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython2.7-minimal armhf 2.7.16-2+deb10u1 [395 kB]
Get:63 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libncurses6 armhf 6.1+20181013-2+deb10u2 [78.9 kB]
Get:64 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libtinfo6 armhf 6.1+20181013-2+deb10u2 [312 kB]
Get:67 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libncursesw6 armhf 6.1+20181013-2+deb10u2 [103 kB]
Get:68 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python3.7 armhf 3.7.3-2+deb10u1 [330 kB]
Get:69 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython3.7 armhf 3.7.3-2+deb10u1 [1,252 kB]
Get:104 http://mirror.datamossa.io/raspbian buster/main armhf ca-certificates all 20200601deb10u1 [158 kB]
Get:70 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython3.7-stdlib armhf 3.7.3-2+deb10u1 [1,662 kB]
Get:71 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf python3.7-minimal armhf 3.7.3-2+deb10u1 [1,463 kB]
Get:72 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libpython3.7-minimal armhf 3.7.3-2+deb10u1 [583 kB]
Get:73 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf openssh-sftp-server armhf 1:7.9p1-10+deb10u2 [35.9 kB]
Get:74 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libcom-err2 armhf 1.44.5-1+deb10u3 [67.6 kB]
Get:75 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf openssh-server armhf 1:7.9p1-10+deb10u2 [291 kB]
Get:76 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf git-man all 1:2.20.1-2+deb10u3 [1,620 kB]
Get:77 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libsasl2-modules-db armhf 2.1.27+dfsg-1+deb10u1 [67.5 kB]
Get:78 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libsasl2-2 armhf 2.1.27+dfsg-1+deb10u1 [98.8 kB]
Get:79 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libldap-common all 2.4.47+dfsg-3+rpi1+deb10u2 [89.8 kB]
Get:80 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libldap-2.4-2 armhf 2.4.47+dfsg-3+rpi1+deb10u2 [198 kB]
Get:81 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libcurl3-gnutls armhf 7.64.0-4+deb10u1 [292 kB]
Get:82 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf git armhf 1:2.20.1-2+deb10u3 [4,194 kB]
Get:83 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf openssh-client armhf 1:7.9p1-10+deb10u2 [670 kB]
Get:85 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf tzdata all 2020a-0+deb10u1 [263 kB]
Get:86 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf iputils-ping armhf 3:20180629-2+deb10u1 [40.2 kB]
Get:87 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf bind9-host armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [268 kB]
Get:88 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libbind9-161 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [243 kB]
Get:89 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libisccfg163 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [258 kB]
Get:90 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libisccc161 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [234 kB]
Get:91 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libdns1104 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [1,078 kB]
Get:92 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libisc1100 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [422 kB]
Get:93 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf liblwres161 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [246 kB]
Get:94 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf file armhf 1:5.35-4+deb10u1 [65.4 kB]
Get:95 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmagic1 armhf 1:5.35-4+deb10u1 [110 kB]
Get:96 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmagic-mgc armhf 1:5.35-4+deb10u1 [242 kB]
Get:97 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf ncurses-term all 6.1+20181013-2+deb10u2 [490 kB]
Get:98 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf binutils-arm-linux-gnueabihf armhf 2.31.1-16+rpi2 [1,814 kB]
Get:112 http://archive.raspberrypi.org/debian buster/main armhf libraspberrypi0 armhf 1.20200723-1 [850 kB]
Get:99 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libbinutils armhf 2.31.1-16+rpi2 [302 kB]
Get:100 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf binutils armhf 2.31.1-16+rpi2 [57.0 kB]
Get:101 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf binutils-common armhf 2.31.1-16+rpi2 [2,075 kB]
Get:114 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-bootloader armhf 1.20200723-1 [4,505 kB]
Get:105 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf curl armhf 7.64.0-4+deb10u1 [254 kB]
Get:106 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libcurl4 armhf 7.64.0-4+deb10u1 [294 kB]
Get:107 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf distro-info-data all 0.41+deb10u2 [6,584 B]
Get:108 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libfribidi0 armhf 1.0.5-3.1+deb10u1 [62.3 kB]
Get:109 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libmysofa0 armhf 0.6dfsg0-3+deb10u1 [34.2 kB]
Get:110 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libopenmpt0 armhf 0.4.3-1+deb10u1 [535 kB]
Get:111 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libssh-gcrypt-4 armhf 0.8.7-1+deb10u1 [171 kB]
Get:113 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libvpx5 armhf 1.7.0-3+deb10u1 [449 kB]
Get:115 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf fuse armhf 2.9.9-1+deb10u1 [69.2 kB]
Get:116 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libfuse2 armhf 2.9.9-1+deb10u1 [116 kB]
Get:117 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf imagemagick-6.q16 armhf 8:6.9.10.23+dfsg-2.1+deb10u1 [580 kB]
Get:118 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf imagemagick armhf 8:6.9.10.23+dfsg-2.1+deb10u1 [156 kB]
Get:119 http://archive.raspberrypi.org/debian buster/main armhf firmware-atheros all 1:20190114-1+rpt7 [3,887 kB]
Get:120 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libklibc armhf 2.0.6-1+rpi1 [52.5 kB]
Get:121 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf klibc-utils armhf 2.0.6-1+rpi1 [87.1 kB]
Get:122 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf initramfs-tools-core all 0.133+deb10u1 [99.2 kB]
Get:123 http://archive.raspberrypi.org/debian buster/main armhf firmware-brcm80211 all 1:20190114-1+rpt7 [4,457 kB]
Get:124 http://mirror.datamossa.io/raspbian buster/main armhf linux-base all 4.6 [32.4 kB]
Get:125 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf initramfs-tools all 0.133+deb10u1 [69.7 kB]
Get:126 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libarchive13 armhf 3.3.3-4+deb10u1 [271 kB]
Get:127 http://archive.raspberrypi.org/debian buster/main armhf firmware-libertas all 1:20190114-1+rpt7 [3,423 kB]
Get:128 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libisc-export1100 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [360 kB]
Get:129 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libdns-export1104 armhf 1:9.11.5.P4+dfsg-5.1+deb10u1 [871 kB]
Get:130 http://archive.raspberrypi.org/debian buster/main armhf firmware-misc-nonfree all 1:20190114-1+rpt7 [3,070 kB]
Get:131 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libglib2.0-data all 2.58.3-2+deb10u2 [1,110 kB]
Get:133 http://archive.raspberrypi.org/debian buster/main armhf firmware-realtek all 1:20190114-1+rpt7 [495 kB]
Get:134 http://archive.raspberrypi.org/debian buster/main armhf libdrm-amdgpu1 armhf 2.4.100-4+rpi1bpo10+1 [26.9 kB]
Get:135 http://archive.raspberrypi.org/debian buster/main armhf libdrm-nouveau2 armhf 2.4.100-4+rpi1bpo10+1 [24.8 kB]
Get:136 http://archive.raspberrypi.org/debian buster/main armhf libdrm-radeon1 armhf 2.4.100-4+rpi1bpo10+1 [29.0 kB]
Get:137 http://archive.raspberrypi.org/debian buster/main armhf libllvm9 armhf 1:9.0.1-6+rpi1bpo10+1 [13.1 MB]
Get:132 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libncursesw5 armhf 6.1+20181013-2+deb10u2 [94.3 kB]
Get:138 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libtinfo5 armhf 6.1+20181013-2+deb10u2 [309 kB]
Get:139 http://mirror.datamossa.io/raspbian buster/main armhf libpango-1.0-0 armhf 1.42.4-8deb10u1 [169 kB]
Get:140 http://mirror.datamossa.io/raspbian buster/main armhf libpangoft2-1.0-0 armhf 1.42.4-8deb10u1 [62.3 kB]
Get:141 http://mirror.datamossa.io/raspbian buster/main armhf libpangocairo-1.0-0 armhf 1.42.4-8deb10u1 [52.0 kB]
Get:142 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libss2 armhf 1.44.5-1+deb10u3 [71.0 kB]
Get:143 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf libxmuu1 armhf 2:1.1.2-2+b3 [23.4 kB]
Get:144 http://archive.raspberrypi.org/debian buster/main armhf libgl1-mesa-dri armhf 19.3.2-1bpo10+1rpt1 [5,550 kB]
Get:145 http://mirror.datamossa.io/raspbian buster/main armhf python-apt-common all 1.8.4.1 [95.7 kB]
Get:146 http://mirror.datamossa.io/raspbian buster/main armhf python3-apt armhf 1.8.4.1 [167 kB]
Get:147 http://archive.raspberrypi.org/debian buster/main armhf libpam-chksshpwd armhf 1.3.1-5+rpt2 [81.7 kB]
Get:148 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-sys-mods armhf 20200514 [10.6 kB]
Get:149 http://archive.raspberrypi.org/debian buster/main armhf pi-bluetooth all 0.1.13 [4,908 B]
Get:150 http://archive.raspberrypi.org/debian buster/main armhf rpi.gpio-common armhf 0.7.0-0.1bpo10+1 [5,776 B]
Get:151 http://archive.raspberrypi.org/debian buster/main armhf python-rpi.gpio armhf 0.7.0-0.1~bpo10+1 [20.8 kB]
Get:152 http://archive.raspberrypi.org/debian buster/main armhf raspi-config all 20200707 [26.4 kB]
Get:153 http://archive.raspberrypi.org/debian buster/main armhf rpi-eeprom-images all 7.8-1 [6,112 B]
Get:154 http://archive.raspberrypi.org/debian buster/main armhf rpi-eeprom all 7.8-1 [316 kB]
Get:155 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf rpcbind armhf 1.2.5-0.3+deb10u1 [41.2 kB]
Get:156 http://archive.raspberrypi.org/debian buster/main armhf rpi-update all 20200409 [7,488 B]
Get:157 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf sudo armhf 1.8.27-1+deb10u2 [1,201 kB]
Get:158 http://mirror.internode.on.net/pub/raspbian/raspbian buster/main armhf wpasupplicant armhf 2:2.7+git20190128+0c1e29f-6+deb10u2 [1,008 kB]
Fetched 258 MB in 2min 11s (1,968 kB/s)

**Comment by Gadgetoid** [comment] 2020-07-27 10:01
Duplicate of https://github.com/pimoroni/hyperpixel4/issues/81

**Closed by Gadgetoid** 2020-07-27 10:01 UTC

**Comment by mikenosko** [comment] 2020-07-27 10:15
Happened to me as well.

I have the 2gb version of pi4 `b03112` and a rectangular hyperpixel4; i run an up-to-date octopi `Raspbian GNU/Linux 10 (buster)` with the `5.4.51-v7l+` kernel the 32bit one (`armv7l`)

Problem started after the last 1-3 updates: `cat /var/log/dpkg.log | grep upgrade`; im 100% sure it was working earlier in the day on the 22 july, so here are the upgrades i did since to narrow it down:

> 2020-07-21 20:48:25 upgrade libnss3:armhf 2:3.42.1-1+deb10u2 2:3.42.1-1+deb10u3
2020-07-21 20:48:26 upgrade libopenmpt0:armhf 0.4.3-1 0.4.3-1+deb10u1
2020-07-21 20:48:26 upgrade libraspberrypi-doc:armhf 1.20200601-1 1.20200717-1
2020-07-21 20:48:29 upgrade libraspberrypi-dev:armhf 1.20200601-1 1.20200717-1
2020-07-21 20:48:29 upgrade raspberrypi-kernel:armhf 1.20200601-1 1.20200717-1
2020-07-21 20:49:23 upgrade libraspberrypi-bin:armhf 1.20200601-1 1.20200717-1
2020-07-21 20:49:24 upgrade libraspberrypi0:armhf 1.20200601-1 1.20200717-1
2020-07-21 20:49:25 upgrade raspberrypi-bootloader:armhf 1.20200601-1 1.20200717-1
2020-07-21 20:49:30 upgrade rpi-eeprom:all 7.5-1 7.8-1
2020-07-25 11:06:44 upgrade libraspberrypi-doc:armhf 1.20200717-1 1.20200723-1
2020-07-25 11:06:47 upgrade libraspberrypi-dev:armhf 1.20200717-1 1.20200723-1
2020-07-25 11:06:49 upgrade raspberrypi-kernel:armhf 1.20200717-1 1.20200723-1
2020-07-25 11:07:55 upgrade libraspberrypi-bin:armhf 1.20200717-1 1.20200723-1
2020-07-25 11:07:56 upgrade libraspberrypi0:armhf 1.20200717-1 1.20200723-1
2020-07-25 11:07:59 upgrade raspberrypi-bootloader:armhf 1.20200717-1 1.20200723-1
2020-07-26 14:31:58 upgrade raspberrypi-kernel:armhf 1.20200723-1 1.20200723-1
2020-07-26 14:33:07 upgrade raspberrypi-bootloader:armhf 1.20200723-1 1.20200723-1

The touch seems to be working - i touched the screen a couple of times as i have the screensaver on for it to wake up and while the screen didn't come on the hotend began to heat up. The screen comes on briefly when restarting and then just blank with no backlight

`dmesg | grep Goodix`

> Goodix-TS 11-005d: 11-005d supply AVDD28 not found, using dummy regulator
Goodix-TS 11-005d: 11-005d supply VDDIO not found, using dummy regulator
Goodix-TS 11-005d: i2c test failed attempt 1: -6
Goodix-TS 11-005d: i2c test failed attempt 2: -6
Goodix-TS 11-005d: I2C communication failure: -6
Goodix-TS 11-0014: 11-0014 supply AVDD28 not found, using dummy regulator
Goodix-TS 11-0014: 11-0014 supply VDDIO not found, using dummy regulator
Goodix-TS 11-0014: ID 911, version: 1060
input: Goodix Capacitive TouchScreen as /devices/platform/i2c@0/i2c-11/11-0014/input/input0

`i2cdetect -y 11` the UU is in 4:10 as per your template
